spring:
  ai:
    ollama:
      embedding:
        model: "llama2"
        options:
          temperature: 0.5
          top-p: 0.2
          top-k: 2
          num-g-p-u: 1
      base-url: "http://localhost:11434"